name: admet_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.3.3
  - scipy=1.9.3
  - scikit-learn
  - rdkit=2023.9.5
  - pandas=2.1.1
  - joblib=1.3.2
  - xgboost=1.7.6
  - flask=3.1.2
  - flask-cors=6.0.1
  - seaborn
  - matplotlib=3.10.1

  - pip:
      - blinker==1.9.0
      - cairocffi==1.7.1
      - CairoSVG==2.8.2
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - colorama==0.4.6
      - cssselect2==0.8.0
      - cycler==0.12.1
      - defusedxml==0.7.1
      - fonttools==4.60.0
      - freetype-py==2.3.0
      - greenlet==3.2.4
      - itsdangerous==2.2.0
      - Jinja2==3.1.6
      - kiwisolver==1.4.9
      - MarkupSafe==3.0.2
      - munkres==1.1.4
      - pillow==11.3.0
      - pycairo==1.23.0
      - pycparser==2.23
      - pyparsing==3.2.5
      - PyQt6==6.7.1
      - PyQt6_sip==13.9.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - reportlab==4.4.4
      - rlPyCairo==0.4.0
      - setuptools==78.1.1
      - sip==6.10.0
      - six==1.17.0
      - SQLAlchemy==2.0.43
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tornado==6.5.1
      - typing_extensions==4.15.0
      - tzdata==2025.2
      - unicodedata2==16.0.0
      - webencodings==0.5.1
      - Werkzeug==3.1.3
      - wheel==0.45.1
      - pip==25.2
